.TH "about.php" 3 "zwa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
about.php \- Obsah souboru pro stránku 'O Nás'\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$user\fP = new \fBLoginUser\fP(null, null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Obsah souboru pro stránku 'O Nás'\&. 

o_nas\&.php 
.SH "Variable Documentation"
.PP 
.SS "$user = new \fBLoginUser\fP(null, null)"

.SH "Author"
.PP 
Generated automatically by Doxygen for zwa from the source code\&.
