.TH "CommentProcessing" 3 "zwa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommentProcessing
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Zpracování komentářů k položkám v aplikaci\&.
.PP
Skript obsahuje funkce pro přidání komentáře k určité položce a následné přesměrování\&. Kontroluje, zda byl odeslán komentář a provádí jeho zpracování a ukládání do JSON souboru\&. Následně přesměrovává zpět na původní stránku s položkou nebo na úvodní stránku\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for zwa from the source code\&.
