.TH "index.php" 3 "zwa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
index.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$user\fP = new \fBLoginUser\fP(null, null)"
.br
.ti -1c
.RI "\fB$names\fP = \fBgetNames\fP()"
.br
.ti -1c
.RI "\fBforeach\fP ( $names as $name)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$names = \fBgetNames\fP()"

.SS "$user = new \fBLoginUser\fP(null, null)"

.SS "foreach($names as $name) ( $names as)"
Prochází jména kolonád a vytváří odkazy a informační boxy pro každou kolonádu\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for zwa from the source code\&.
