.TH "Registration" 3 "zwa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Registration
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Registrace nového uživatele\&.
.PP
Tento skript zpracovává přihlášení nového uživatele\&. V případě úspěšné registrace přesměruje uživatele na přihlašovací stránku\&. Obsahuje také ochranu proti CSRF útokům\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for zwa from the source code\&.
