.TH "RegisterUser" 3 "zwa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterUser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($username, $email, $password, $password2, $gender, $image)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB$error\fP = array()"
.br
.ti -1c
.RI "\fB$success\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RegisterUser::__construct ( $username,  $email,  $password,  $password2,  $gender,  $image)"
Konstruktor třídy \fBRegisterUser\fP\&.
.PP
\fBParameters\fP
.RS 4
\fI$username\fP Jméno uživatele\&. 
.br
\fI$email\fP Email uživatele\&. 
.br
\fI$password\fP Nezašifrované heslo uživatele\&. 
.br
\fI$password2\fP Potvrzení hesla uživatele\&. 
.br
\fI$gender\fP Pohlaví uživatele\&. 
.br
\fI$image\fP Informace o nahraném obrázku uživatele\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "RegisterUser::$error = array()"

.SS "RegisterUser::$success"


.SH "Author"
.PP 
Generated automatically by Doxygen for zwa from the source code\&.
