.TH "ServerValidation" 3 "zwa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerValidation
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Serverová validace vstupních dat pro registraci uživatele\&.
.PP
Tento skript zpracovává POST požadavky pro validaci vstupních dat na serverové straně\&. Obsahuje validaci pro jednotlivá pole jako jméno, e-mail a heslo\&. Výsledek validace je odeslán ve formátu JSON\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for zwa from the source code\&.
